/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of XMMSClient.xs. Do not edit this file, edit XMMSClient.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "../src/clients/lib/perl/XMMSClient.xs"
#include "perl_xmmsclient.h"

STATIC void
disconnect_callback_set_cb (void *userdata)
{
	PerlXMMSClientCallback *cb = (PerlXMMSClientCallback *)userdata;

	perl_xmmsclient_callback_invoke (cb, NULL);
}

void
perl_xmmsclient_xmmsc_io_need_out_callback_set_cb (int flag, void *userdata)
{
	PerlXMMSClientCallback *cb = (PerlXMMSClientCallback *)userdata;

	perl_xmmsclient_callback_invoke (cb, NULL);
}

#line 29 "../src/clients/lib/perl/XMMSClient.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 72 "../src/clients/lib/perl/XMMSClient.c"

XS(XS_Audio__XMMSClient_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "class, clientname=NULL");
    {
	const char *	class = (const char *)SvPV_nolen(ST(0));
	const char *	clientname;
#line 68 "../src/clients/lib/perl/XMMSClient.xs"
		xmmsc_connection_t *con;
#line 89 "../src/clients/lib/perl/XMMSClient.c"
	SV *	RETVAL;

	if (items < 2)
	    clientname = NULL;
	else {
	    clientname = (const char *)SvPV_nolen(ST(1));
	}
#line 70 "../src/clients/lib/perl/XMMSClient.xs"
		if (!clientname) {
			clientname = SvPV_nolen (get_sv ("0", 0));
		}
#line 101 "../src/clients/lib/perl/XMMSClient.c"
#line 74 "../src/clients/lib/perl/XMMSClient.xs"
		con = xmmsc_init (clientname);

		if (con == NULL) {
			RETVAL = &PL_sv_undef;
		}
		else {
			RETVAL = perl_xmmsclient_new_sv_from_ptr (con, class);
		}
#line 111 "../src/clients/lib/perl/XMMSClient.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_connect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_connect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "c, ipcpath=NULL");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	ipcpath;
	int	RETVAL;
	dXSTARG;

	if (items < 2)
	    ipcpath = NULL;
	else {
	    ipcpath = (const char *)SvPV_nolen(ST(1));
	}

	RETVAL = xmmsc_connect(c, ipcpath);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_disconnect_callback_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_disconnect_callback_set)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "c, func, data=NULL");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	SV *	func = ST(1);
	SV *	data;
#line 137 "../src/clients/lib/perl/XMMSClient.xs"
		PerlXMMSClientCallback *cb = NULL;
		PerlXMMSClientCallbackParamType param_types[1];
#line 165 "../src/clients/lib/perl/XMMSClient.c"

	if (items < 3)
	    data = NULL;
	else {
	    data = ST(2);
	}
#line 140 "../src/clients/lib/perl/XMMSClient.xs"
		param_types[0] = PERL_XMMSCLIENT_CALLBACK_PARAM_TYPE_CONNECTION;

		cb = perl_xmmsclient_callback_new (func, data, ST(0), 1, param_types,
		                                   PERL_XMMSCLIENT_CALLBACK_RETURN_TYPE_NONE);

		xmmsc_disconnect_callback_set_full (c, disconnect_callback_set_cb, cb,
		                                    (xmmsc_user_data_free_func_t)perl_xmmsclient_callback_destroy);
#line 180 "../src/clients/lib/perl/XMMSClient.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Audio__XMMSClient_io_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_io_disconnect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");

	xmmsc_io_disconnect(c);
    }
    XSRETURN_EMPTY;
}


XS(XS_Audio__XMMSClient_get_last_error); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_get_last_error)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	char *	RETVAL;
	dXSTARG;

	RETVAL = xmmsc_get_last_error(c);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_main_list_plugins); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_main_list_plugins)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "c, type=XMMS_PLUGIN_TYPE_ALL");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmms_plugin_type_t	type;
	xmmsc_result_t *	RETVAL;

	if (items < 2)
	    type = XMMS_PLUGIN_TYPE_ALL;
	else {
	    {
		    char *plugin_type = NULL;
		    if (ST(1) == NULL) {
			    plugin_type = "";
		    } else {
			    plugin_type = SvPV_nolen (ST(1));
		    }

		    if (strcmp (plugin_type, "output") == 0) {
			    type = XMMS_PLUGIN_TYPE_OUTPUT;
		    } else if (strcmp (plugin_type, "xform") == 0) {
			    type = XMMS_PLUGIN_TYPE_XFORM;
		    } else if (strcmp (plugin_type, "all") == 0) {
			    type = XMMS_PLUGIN_TYPE_ALL;
		    } else {
			    croak ("unknown XMMS_PLUGIN_TYPE_T: %s", plugin_type);
		    }
	    };
	}

	RETVAL = xmmsc_main_list_plugins(c, type);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_main_stats); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_main_stats)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_main_stats(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_quit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_quit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_quit(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_quit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_quit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_quit(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_get_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_get_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, url");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	url = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_get_id(c, url);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_move_entry); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_move_entry)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, id, url");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	url = (const char *)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_move_entry(c, id, url);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_remove_entry); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_remove_entry)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, entry");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int	entry = (int)SvIV(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_remove_entry(c, entry);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_add_entry); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_add_entry)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, url");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	url = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_add_entry(c, url);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_add_entry_args); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_add_entry_args)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       croak_xs_usage(cv,  "c, url, ...");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	url = (const char *)SvPV_nolen(ST(1));
#line 405 "../src/clients/lib/perl/XMMSClient.xs"
		int i;
		int nargs;
		const char **args;
#line 457 "../src/clients/lib/perl/XMMSClient.c"
	xmmsc_result_t *	RETVAL;
#line 409 "../src/clients/lib/perl/XMMSClient.xs"
		nargs = items - 2;
		args = (const char **)malloc (sizeof (char *) * nargs);

		for (i = 2; i < items; i++) {
			args[i] = SvPV_nolen (ST (i));
		}
#line 466 "../src/clients/lib/perl/XMMSClient.c"

	RETVAL = xmmsc_medialib_add_entry_args(c, url, nargs, args);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
#line 418 "../src/clients/lib/perl/XMMSClient.xs"
		free (args);
#line 474 "../src/clients/lib/perl/XMMSClient.c"
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_add_entry_encoded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_add_entry_encoded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, url");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	url = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_add_entry_encoded(c, url);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playlist); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playlist)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "c, playlist=XMMS_ACTIVE_PLAYLIST");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	playlist;
	perl_xmmsclient_playlist_t *	RETVAL;

	if (items < 2)
	    playlist = XMMS_ACTIVE_PLAYLIST;
	else {
	    playlist = (const char *)SvPV_nolen(ST(1));
	}
#line 464 "../src/clients/lib/perl/XMMSClient.xs"
		RETVAL = perl_xmmsclient_playlist_new (c, playlist);
#line 526 "../src/clients/lib/perl/XMMSClient.c"
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Playlist");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_path_import); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_path_import)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, path");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	path = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_path_import(c, path);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_path_import_encoded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_path_import_encoded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, path");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	path = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_path_import_encoded(c, path);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_rehash); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_rehash)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "c, id=0");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id;
	xmmsc_result_t *	RETVAL;

	if (items < 2)
	    id = 0;
	else {
	    id = (uint32_t)SvUV(ST(1));
	}

	RETVAL = xmmsc_medialib_rehash(c, id);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_get_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_get_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, id");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_get_info(c, id);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_medialib_entry_added); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_medialib_entry_added)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_medialib_entry_added(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_medialib_entry_changed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_medialib_entry_changed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_medialib_entry_changed(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_entry_property_set_int); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_entry_property_set_int)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "c, id, key, value");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	key = (const char *)SvPV_nolen(ST(2));
	int	value = (int)SvIV(ST(3));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_entry_property_set_int(c, id, key, value);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_entry_property_set_int_with_source); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_entry_property_set_int_with_source)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "c, id, source, key, value");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	source = (const char *)SvPV_nolen(ST(2));
	const char *	key = (const char *)SvPV_nolen(ST(3));
	int	value = (int)SvIV(ST(4));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_entry_property_set_int_with_source(c, id, source, key, value);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_entry_property_set_str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_entry_property_set_str)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "c, id, key, value");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	key = (const char *)SvPV_nolen(ST(2));
	const char *	value = (const char *)SvPV_nolen(ST(3));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_entry_property_set_str(c, id, key, value);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_entry_property_set_str_with_source); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_entry_property_set_str_with_source)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "c, id, source, key, value");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	source = (const char *)SvPV_nolen(ST(2));
	const char *	key = (const char *)SvPV_nolen(ST(3));
	const char *	value = (const char *)SvPV_nolen(ST(4));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_entry_property_set_str_with_source(c, id, source, key, value);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_entry_property_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_entry_property_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, id, key");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	key = (const char *)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_entry_property_remove(c, id, key);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_medialib_entry_property_remove_with_source); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_medialib_entry_property_remove_with_source)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "c, id, source, key");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	id = (uint32_t)SvUV(ST(1));
	const char *	source = (const char *)SvPV_nolen(ST(2));
	const char *	key = (const char *)SvPV_nolen(ST(3));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_medialib_entry_property_remove_with_source(c, id, source, key);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_get); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_get)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, collname, namespace");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	collname = (const char *)SvPV_nolen(ST(1));
	xmmsv_coll_namespace_t	namespace = (xmmsv_coll_namespace_t)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_get(c, collname, namespace);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_sync); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_sync)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_sync(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_list); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_list)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, namespace");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsv_coll_namespace_t	namespace = (xmmsv_coll_namespace_t)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_list(c, namespace);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "c, coll, name, namespace");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsv_coll_t *	coll = (xmmsv_coll_t *)perl_xmmsclient_get_ptr_from_sv (ST(1), "Audio::XMMSClient::Collection");
	const char *	name = (const char *)SvPV_nolen(ST(2));
	xmmsv_coll_namespace_t	namespace = (xmmsv_coll_namespace_t)SvPV_nolen(ST(3));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_save(c, coll, name, namespace);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, name, namespace");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	name = (const char *)SvPV_nolen(ST(1));
	xmmsv_coll_namespace_t	namespace = (xmmsv_coll_namespace_t)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_remove(c, name, namespace);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, mediaid, namespace");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	unsigned int	mediaid = (unsigned int)SvUV(ST(1));
	xmmsv_coll_namespace_t	namespace = (xmmsv_coll_namespace_t)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_find(c, mediaid, namespace);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_rename); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_rename)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "c, from, to, namespace");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	char *	from = (char *)SvPV_nolen(ST(1));
	char *	to = (char *)SvPV_nolen(ST(2));
	xmmsv_coll_namespace_t	namespace = (xmmsv_coll_namespace_t)SvPV_nolen(ST(3));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_rename(c, from, to, namespace);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_query_ids); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_query_ids)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       croak_xs_usage(cv,  "c, coll, ...");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsv_coll_t *	coll = (xmmsv_coll_t *)perl_xmmsclient_get_ptr_from_sv (ST(1), "Audio::XMMSClient::Collection");
	xmmsc_result_t *	RETVAL;
#line 953 "../src/clients/lib/perl/XMMSClient.xs"
		xmmsv_t *order = NULL;
		unsigned int limit_start = 0;
		unsigned int limit_len = 0;
		HV *args;
		SV *val;

		if (items == 3 && SvROK (ST (2)) && (SvTYPE (SvRV (ST (2))) == SVt_PVHV)) {
			args = (HV *)SvRV (ST (2));

			if ((val = perl_xmmsclient_hv_fetch (args, "order", 5))) {
				order = perl_xmmsclient_pack_stringlist (val);
			}

			if ((val = perl_xmmsclient_hv_fetch (args, "limit_start", 11))) {
				limit_start = SvUV (val);
			}

			if ((val = perl_xmmsclient_hv_fetch (args, "limit_len", 9))) {
				limit_len = SvUV (val);
			}
		}
		else {
			order = perl_xmmsclient_pack_stringlist (ST (2));
			limit_start = SvOK (ST (3)) ? SvUV (ST (3)) : 0;
			limit_len = SvOK (ST (4)) ? SvUV (ST (4)) : 0;
		}
#line 1055 "../src/clients/lib/perl/XMMSClient.c"

	RETVAL = xmmsc_coll_query_ids(c, coll, order, limit_start, limit_len);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
#line 982 "../src/clients/lib/perl/XMMSClient.xs"
		xmmsv_unref (order);
#line 1063 "../src/clients/lib/perl/XMMSClient.c"
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_query_infos); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_query_infos)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       croak_xs_usage(cv,  "c, coll, ...");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsv_coll_t *	coll = (xmmsv_coll_t *)perl_xmmsclient_get_ptr_from_sv (ST(1), "Audio::XMMSClient::Collection");
	xmmsc_result_t *	RETVAL;
#line 1043 "../src/clients/lib/perl/XMMSClient.xs"
		xmmsv_t *order = NULL;
		unsigned int limit_start = 0;
		unsigned int limit_len = 0;
		xmmsv_t *fetch = NULL;
		xmmsv_t *group = NULL;
		HV *args;
		SV *val;

		if (items == 3 && SvROK (ST (2)) && (SvTYPE (SvRV (ST (2))) == SVt_PVHV)) {
			args = (HV *)SvRV (ST (2));

			if ((val = perl_xmmsclient_hv_fetch (args, "order", 5))) {
				order = perl_xmmsclient_pack_stringlist (val);
			}

			if ((val = perl_xmmsclient_hv_fetch (args, "fetch", 5))) {
				fetch = perl_xmmsclient_pack_stringlist (val);
			}

			if ((val = perl_xmmsclient_hv_fetch (args, "group", 5))) {
				group = perl_xmmsclient_pack_stringlist (val);
			}

			if ((val = perl_xmmsclient_hv_fetch (args, "limit_start", 11))) {
				limit_start = SvUV (val);
			}

			if ((val = perl_xmmsclient_hv_fetch (args, "limit_len", 9))) {
				limit_len = SvUV (val);
			}
		}
		else {
			order = perl_xmmsclient_pack_stringlist (ST (2));
			limit_start = SvOK (ST (3)) ? SvUV (ST (3)) : 0;
			limit_len = SvOK (ST (4)) ? SvUV (ST (4)) : 0;
			fetch = perl_xmmsclient_pack_stringlist (ST (5));
			group = perl_xmmsclient_pack_stringlist (ST (6));
		}
#line 1122 "../src/clients/lib/perl/XMMSClient.c"

	RETVAL = xmmsc_coll_query_infos(c, coll, order, limit_start, limit_len, fetch, group);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
#line 1084 "../src/clients/lib/perl/XMMSClient.xs"
		xmmsv_unref (order);
		xmmsv_unref (fetch);
		xmmsv_unref (group);
#line 1132 "../src/clients/lib/perl/XMMSClient.c"
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_collection_changed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_collection_changed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_collection_changed(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_xform_media_browse); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_xform_media_browse)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, url");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	url = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_xform_media_browse(c, url);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_xform_media_browse_encoded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_xform_media_browse_encoded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, url");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	url = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_xform_media_browse_encoded(c, url);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_bindata_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_bindata_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, data");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
#line 1177 "../src/clients/lib/perl/XMMSClient.xs"
		STRLEN len = 0;
#line 1223 "../src/clients/lib/perl/XMMSClient.c"
	const unsigned char *	data = (const unsigned char *)SvPVbyte (ST(1), len);
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_bindata_add(c, data, len);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_bindata_retrieve); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_bindata_retrieve)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, hash");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	hash = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_bindata_retrieve(c, hash);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_bindata_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_bindata_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, hash");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	hash = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_bindata_remove(c, hash);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_bindata_list); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_bindata_list)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_bindata_list(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_config_register_value); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_config_register_value)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, valuename, defaultvalue");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	valuename = (const char *)SvPV_nolen(ST(1));
	const char *	defaultvalue = (const char *)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_config_register_value(c, valuename, defaultvalue);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_config_set_value); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_config_set_value)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, key, val");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	key = (const char *)SvPV_nolen(ST(1));
	const char *	val = (const char *)SvPV_nolen(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_config_set_value(c, key, val);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_config_get_value); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_config_get_value)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, key");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	key = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_config_get_value(c, key);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_config_list_values); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_config_list_values)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_config_list_values(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_config_value_changed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_config_value_changed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_config_value_changed(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_mediainfo_reader_status); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_mediainfo_reader_status)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_mediainfo_reader_status(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_signal_mediainfo_reader_unindexed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_signal_mediainfo_reader_unindexed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_signal_mediainfo_reader_unindexed(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_userconfdir_get); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_userconfdir_get)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
#line 1411 "../src/clients/lib/perl/XMMSClient.xs"
		char path[XMMS_PATH_MAX];
#line 1486 "../src/clients/lib/perl/XMMSClient.c"
	const char *	RETVAL;
	dXSTARG;
#line 1413 "../src/clients/lib/perl/XMMSClient.xs"
		RETVAL = xmmsc_userconfdir_get (path, XMMS_PATH_MAX);
#line 1491 "../src/clients/lib/perl/XMMSClient.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_tickle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_tickle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_tickle(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_stop); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_stop)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_stop(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_pause); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_pause)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_pause(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_start); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_start)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_start(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_seek_ms); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_seek_ms)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "c, milliseconds, whence = XMMS_PLAYBACK_SEEK_SET");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int32_t	milliseconds = (int32_t)SvIV(ST(1));
	xmms_playback_seek_mode_t	whence;
	xmmsc_result_t *	RETVAL;

	if (items < 3)
	    whence = XMMS_PLAYBACK_SEEK_SET;
	else {
	    {
		    char *seek_type = SvPV_nolen (ST(2));

		    if (strcmp (seek_type, "cur") == 0) {
			    whence = XMMS_PLAYBACK_SEEK_CUR;
		    }
		    else if (strcmp (seek_type, "set") == 0) {
			    whence = XMMS_PLAYBACK_SEEK_SET;
		    }
		    else {
			    croak ("unknown XMMSV_PLAYBACK_SEEK_MODE_T: %s", seek_type);
		    }
	    };
	}

	RETVAL = xmmsc_playback_seek_ms(c, milliseconds, whence);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_seek_samples); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_seek_samples)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "c, samples, whence = XMMS_PLAYBACK_SEEK_SET");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int32_t	samples = (int32_t)SvIV(ST(1));
	xmms_playback_seek_mode_t	whence;
	xmmsc_result_t *	RETVAL;

	if (items < 3)
	    whence = XMMS_PLAYBACK_SEEK_SET;
	else {
	    {
		    char *seek_type = SvPV_nolen (ST(2));

		    if (strcmp (seek_type, "cur") == 0) {
			    whence = XMMS_PLAYBACK_SEEK_CUR;
		    }
		    else if (strcmp (seek_type, "set") == 0) {
			    whence = XMMS_PLAYBACK_SEEK_SET;
		    }
		    else {
			    croak ("unknown XMMSV_PLAYBACK_SEEK_MODE_T: %s", seek_type);
		    }
	    };
	}

	RETVAL = xmmsc_playback_seek_samples(c, samples, whence);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_playback_status); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_playback_status)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_playback_status(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_status); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_status)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_status(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_playback_current_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_playback_current_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_playback_current_id(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_current_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_current_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_current_id(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_signal_playback_playtime); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_signal_playback_playtime)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_signal_playback_playtime(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_playtime); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_playtime)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_playtime(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_volume_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_volume_set)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "c, channel, volume");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	channel = (const char *)SvPV_nolen(ST(1));
	uint32_t	volume = (uint32_t)SvUV(ST(2));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_volume_set(c, channel, volume);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playback_volume_get); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playback_volume_get)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playback_volume_get(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_playback_volume_changed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_playback_volume_changed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_playback_volume_changed(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playlist_list); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playlist_list)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playlist_list(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_playlist_changed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_playlist_changed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_playlist_changed(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_playlist_current_pos); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_playlist_current_pos)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_playlist_current_pos(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_broadcast_playlist_loaded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_broadcast_playlist_loaded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_broadcast_playlist_loaded(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playlist_current_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playlist_current_active)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playlist_current_active(c);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playlist_set_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playlist_set_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, pos");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	uint32_t	pos = (uint32_t)SvUV(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playlist_set_next(c, pos);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_playlist_set_next_rel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_playlist_set_next_rel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, pos");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int32_t	pos = (int32_t)SvIV(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_playlist_set_next_rel(c, pos);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_coll_idlist_from_playlist_file); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_coll_idlist_from_playlist_file)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "c, path");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	const char *	path = (const char *)SvPV_nolen(ST(1));
	xmmsc_result_t *	RETVAL;

	RETVAL = xmmsc_coll_idlist_from_playlist_file(c, path);
	ST(0) = perl_xmmsclient_new_sv_from_ptr (RETVAL, "Audio::XMMSClient::Result");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_io_want_out); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_io_want_out)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int	RETVAL;
	dXSTARG;

	RETVAL = xmmsc_io_want_out(c);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_io_out_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_io_out_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int	RETVAL;
	dXSTARG;

	RETVAL = xmmsc_io_out_handle(c);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_io_in_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_io_in_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int	RETVAL;
	dXSTARG;

	RETVAL = xmmsc_io_in_handle(c);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_io_fd_get); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_io_fd_get)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	int	RETVAL;
	dXSTARG;

	RETVAL = xmmsc_io_fd_get(c);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Audio__XMMSClient_io_need_out_callback_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_io_need_out_callback_set)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "c, func, data=NULL");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
	SV *	func = ST(1);
	SV *	data;
#line 2026 "../src/clients/lib/perl/XMMSClient.xs"
		PerlXMMSClientCallback *cb = NULL;
		PerlXMMSClientCallbackParamType param_types[2];
#line 2177 "../src/clients/lib/perl/XMMSClient.c"

	if (items < 3)
	    data = NULL;
	else {
	    data = ST(2);
	}
#line 2029 "../src/clients/lib/perl/XMMSClient.xs"
		param_types[0] = PERL_XMMSCLIENT_CALLBACK_PARAM_TYPE_CONNECTION;
		param_types[1] = PERL_XMMSCLIENT_CALLBACK_PARAM_TYPE_FLAG;

		cb = perl_xmmsclient_callback_new (func, data, ST(0), 2, param_types,
		                                   PERL_XMMSCLIENT_CALLBACK_RETURN_TYPE_NONE);

		xmmsc_io_need_out_callback_set_full (c,
		                                     perl_xmmsclient_xmmsc_io_need_out_callback_set_cb, cb,
		                                     (xmmsc_user_data_free_func_t)perl_xmmsclient_callback_destroy);
#line 2194 "../src/clients/lib/perl/XMMSClient.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Audio__XMMSClient_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Audio__XMMSClient_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	xmmsc_connection_t *	c = (xmmsc_connection_t *)perl_xmmsclient_get_ptr_from_sv (ST(0), "Audio::XMMSClient");
#line 2074 "../src/clients/lib/perl/XMMSClient.xs"
		xmmsc_unref (c);
#line 2214 "../src/clients/lib/perl/XMMSClient.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Audio__XMMSClient); /* prototype to pass -Wmissing-prototypes */
XS(boot_Audio__XMMSClient)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Audio::XMMSClient::new", XS_Audio__XMMSClient_new, file);
        newXS("Audio::XMMSClient::connect", XS_Audio__XMMSClient_connect, file);
        newXS("Audio::XMMSClient::disconnect_callback_set", XS_Audio__XMMSClient_disconnect_callback_set, file);
        newXS("Audio::XMMSClient::io_disconnect", XS_Audio__XMMSClient_io_disconnect, file);
        newXS("Audio::XMMSClient::get_last_error", XS_Audio__XMMSClient_get_last_error, file);
        newXS("Audio::XMMSClient::main_list_plugins", XS_Audio__XMMSClient_main_list_plugins, file);
        newXS("Audio::XMMSClient::main_stats", XS_Audio__XMMSClient_main_stats, file);
        newXS("Audio::XMMSClient::quit", XS_Audio__XMMSClient_quit, file);
        newXS("Audio::XMMSClient::broadcast_quit", XS_Audio__XMMSClient_broadcast_quit, file);
        newXS("Audio::XMMSClient::medialib_get_id", XS_Audio__XMMSClient_medialib_get_id, file);
        newXS("Audio::XMMSClient::medialib_move_entry", XS_Audio__XMMSClient_medialib_move_entry, file);
        newXS("Audio::XMMSClient::medialib_remove_entry", XS_Audio__XMMSClient_medialib_remove_entry, file);
        newXS("Audio::XMMSClient::medialib_add_entry", XS_Audio__XMMSClient_medialib_add_entry, file);
        newXS("Audio::XMMSClient::medialib_add_entry_args", XS_Audio__XMMSClient_medialib_add_entry_args, file);
        newXS("Audio::XMMSClient::medialib_add_entry_encoded", XS_Audio__XMMSClient_medialib_add_entry_encoded, file);
        newXS("Audio::XMMSClient::playlist", XS_Audio__XMMSClient_playlist, file);
        newXS("Audio::XMMSClient::medialib_path_import", XS_Audio__XMMSClient_medialib_path_import, file);
        newXS("Audio::XMMSClient::medialib_path_import_encoded", XS_Audio__XMMSClient_medialib_path_import_encoded, file);
        newXS("Audio::XMMSClient::medialib_rehash", XS_Audio__XMMSClient_medialib_rehash, file);
        newXS("Audio::XMMSClient::medialib_get_info", XS_Audio__XMMSClient_medialib_get_info, file);
        newXS("Audio::XMMSClient::broadcast_medialib_entry_added", XS_Audio__XMMSClient_broadcast_medialib_entry_added, file);
        newXS("Audio::XMMSClient::broadcast_medialib_entry_changed", XS_Audio__XMMSClient_broadcast_medialib_entry_changed, file);
        newXS("Audio::XMMSClient::medialib_entry_property_set_int", XS_Audio__XMMSClient_medialib_entry_property_set_int, file);
        newXS("Audio::XMMSClient::medialib_entry_property_set_int_with_source", XS_Audio__XMMSClient_medialib_entry_property_set_int_with_source, file);
        newXS("Audio::XMMSClient::medialib_entry_property_set_str", XS_Audio__XMMSClient_medialib_entry_property_set_str, file);
        newXS("Audio::XMMSClient::medialib_entry_property_set_str_with_source", XS_Audio__XMMSClient_medialib_entry_property_set_str_with_source, file);
        newXS("Audio::XMMSClient::medialib_entry_property_remove", XS_Audio__XMMSClient_medialib_entry_property_remove, file);
        newXS("Audio::XMMSClient::medialib_entry_property_remove_with_source", XS_Audio__XMMSClient_medialib_entry_property_remove_with_source, file);
        newXS("Audio::XMMSClient::coll_get", XS_Audio__XMMSClient_coll_get, file);
        newXS("Audio::XMMSClient::coll_sync", XS_Audio__XMMSClient_coll_sync, file);
        newXS("Audio::XMMSClient::coll_list", XS_Audio__XMMSClient_coll_list, file);
        newXS("Audio::XMMSClient::coll_save", XS_Audio__XMMSClient_coll_save, file);
        newXS("Audio::XMMSClient::coll_remove", XS_Audio__XMMSClient_coll_remove, file);
        newXS("Audio::XMMSClient::coll_find", XS_Audio__XMMSClient_coll_find, file);
        newXS("Audio::XMMSClient::coll_rename", XS_Audio__XMMSClient_coll_rename, file);
        newXS("Audio::XMMSClient::coll_query_ids", XS_Audio__XMMSClient_coll_query_ids, file);
        newXS("Audio::XMMSClient::coll_query_infos", XS_Audio__XMMSClient_coll_query_infos, file);
        newXS("Audio::XMMSClient::broadcast_collection_changed", XS_Audio__XMMSClient_broadcast_collection_changed, file);
        newXS("Audio::XMMSClient::xform_media_browse", XS_Audio__XMMSClient_xform_media_browse, file);
        newXS("Audio::XMMSClient::xform_media_browse_encoded", XS_Audio__XMMSClient_xform_media_browse_encoded, file);
        newXS("Audio::XMMSClient::bindata_add", XS_Audio__XMMSClient_bindata_add, file);
        newXS("Audio::XMMSClient::bindata_retrieve", XS_Audio__XMMSClient_bindata_retrieve, file);
        newXS("Audio::XMMSClient::bindata_remove", XS_Audio__XMMSClient_bindata_remove, file);
        newXS("Audio::XMMSClient::bindata_list", XS_Audio__XMMSClient_bindata_list, file);
        newXS("Audio::XMMSClient::config_register_value", XS_Audio__XMMSClient_config_register_value, file);
        newXS("Audio::XMMSClient::config_set_value", XS_Audio__XMMSClient_config_set_value, file);
        newXS("Audio::XMMSClient::config_get_value", XS_Audio__XMMSClient_config_get_value, file);
        newXS("Audio::XMMSClient::config_list_values", XS_Audio__XMMSClient_config_list_values, file);
        newXS("Audio::XMMSClient::broadcast_config_value_changed", XS_Audio__XMMSClient_broadcast_config_value_changed, file);
        newXS("Audio::XMMSClient::broadcast_mediainfo_reader_status", XS_Audio__XMMSClient_broadcast_mediainfo_reader_status, file);
        newXS("Audio::XMMSClient::signal_mediainfo_reader_unindexed", XS_Audio__XMMSClient_signal_mediainfo_reader_unindexed, file);
        newXS("Audio::XMMSClient::userconfdir_get", XS_Audio__XMMSClient_userconfdir_get, file);
        newXS("Audio::XMMSClient::playback_tickle", XS_Audio__XMMSClient_playback_tickle, file);
        newXS("Audio::XMMSClient::playback_stop", XS_Audio__XMMSClient_playback_stop, file);
        newXS("Audio::XMMSClient::playback_pause", XS_Audio__XMMSClient_playback_pause, file);
        newXS("Audio::XMMSClient::playback_start", XS_Audio__XMMSClient_playback_start, file);
        newXS("Audio::XMMSClient::playback_seek_ms", XS_Audio__XMMSClient_playback_seek_ms, file);
        newXS("Audio::XMMSClient::playback_seek_samples", XS_Audio__XMMSClient_playback_seek_samples, file);
        newXS("Audio::XMMSClient::broadcast_playback_status", XS_Audio__XMMSClient_broadcast_playback_status, file);
        newXS("Audio::XMMSClient::playback_status", XS_Audio__XMMSClient_playback_status, file);
        newXS("Audio::XMMSClient::broadcast_playback_current_id", XS_Audio__XMMSClient_broadcast_playback_current_id, file);
        newXS("Audio::XMMSClient::playback_current_id", XS_Audio__XMMSClient_playback_current_id, file);
        newXS("Audio::XMMSClient::signal_playback_playtime", XS_Audio__XMMSClient_signal_playback_playtime, file);
        newXS("Audio::XMMSClient::playback_playtime", XS_Audio__XMMSClient_playback_playtime, file);
        newXS("Audio::XMMSClient::playback_volume_set", XS_Audio__XMMSClient_playback_volume_set, file);
        newXS("Audio::XMMSClient::playback_volume_get", XS_Audio__XMMSClient_playback_volume_get, file);
        newXS("Audio::XMMSClient::broadcast_playback_volume_changed", XS_Audio__XMMSClient_broadcast_playback_volume_changed, file);
        newXS("Audio::XMMSClient::playlist_list", XS_Audio__XMMSClient_playlist_list, file);
        newXS("Audio::XMMSClient::broadcast_playlist_changed", XS_Audio__XMMSClient_broadcast_playlist_changed, file);
        newXS("Audio::XMMSClient::broadcast_playlist_current_pos", XS_Audio__XMMSClient_broadcast_playlist_current_pos, file);
        newXS("Audio::XMMSClient::broadcast_playlist_loaded", XS_Audio__XMMSClient_broadcast_playlist_loaded, file);
        newXS("Audio::XMMSClient::playlist_current_active", XS_Audio__XMMSClient_playlist_current_active, file);
        newXS("Audio::XMMSClient::playlist_set_next", XS_Audio__XMMSClient_playlist_set_next, file);
        newXS("Audio::XMMSClient::playlist_set_next_rel", XS_Audio__XMMSClient_playlist_set_next_rel, file);
        newXS("Audio::XMMSClient::coll_idlist_from_playlist_file", XS_Audio__XMMSClient_coll_idlist_from_playlist_file, file);
        newXS("Audio::XMMSClient::io_want_out", XS_Audio__XMMSClient_io_want_out, file);
        newXS("Audio::XMMSClient::io_out_handle", XS_Audio__XMMSClient_io_out_handle, file);
        newXS("Audio::XMMSClient::io_in_handle", XS_Audio__XMMSClient_io_in_handle, file);
        newXS("Audio::XMMSClient::io_fd_get", XS_Audio__XMMSClient_io_fd_get, file);
        newXS("Audio::XMMSClient::io_need_out_callback_set", XS_Audio__XMMSClient_io_need_out_callback_set, file);
        newXS("Audio::XMMSClient::DESTROY", XS_Audio__XMMSClient_DESTROY, file);

    /* Initialisation Section */

#line 2123 "../src/clients/lib/perl/XMMSClient.xs"
	PERL_UNUSED_VAR (items);
	PERL_XMMSCLIENT_CALL_BOOT (boot_Audio__XMMSClient__Playlist);
	PERL_XMMSCLIENT_CALL_BOOT (boot_Audio__XMMSClient__Collection);
	PERL_XMMSCLIENT_CALL_BOOT (boot_Audio__XMMSClient__Result);

#line 2326 "../src/clients/lib/perl/XMMSClient.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

