AR = 'arm-arago-linux-gnueabi-ar'
ARCHDIR_PERL = '/usr/local/lib/perl/5.10.1'
ARFLAGS = 'rcs'
BINDIR = '/usr/bin'
BISON = '/usr/bin/bison'
BISONFLAGS = ['-d', '--verbose']
BUILD_XMMS2D = True
CC = ['arm-arago-linux-gnueabi-gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('4', '5', '3')
CFLAGS = ['-I/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include', '-g', '-O0', '-Wall', '-Wempty-body', '-Wformat=2', '-Wformat-nonliteral', '-Wformat-security', '-Wignored-qualifiers', '-Wmissing-prototypes', '-Wstrict-prototypes', '-Wtype-limits', '-Wwrite-strings', '-Wno-format-extra-args', '-Wno-format-zero-length', '-fdiagnostics-show-option', '-Werror=implicit-function-declaration']
CFLAGS_DISABLE_ALL = ['-Wno-all']
CFLAGS_DISABLE_DIAGNOSTICSSHOWOPTION = ['-fno-diagnostics-show-option']
CFLAGS_DISABLE_EMPTYBODY = ['-Wno-empty-body']
CFLAGS_DISABLE_FORMAT2 = ['-Wno-format=2']
CFLAGS_DISABLE_FORMATEXTRAARGS = ['-Wno-format-extra-args']
CFLAGS_DISABLE_FORMATNONLITERAL = ['-Wno-format-nonliteral']
CFLAGS_DISABLE_FORMATSECURITY = ['-Wno-format-security']
CFLAGS_DISABLE_FORMATZEROLENGTH = ['-Wno-format-zero-length']
CFLAGS_DISABLE_IGNOREDQUALIFIERS = ['-Wno-ignored-qualifiers']
CFLAGS_DISABLE_IMPLICITFUNCTIONDECLARATION = ['-Wno-error=implicit-function-declaration']
CFLAGS_DISABLE_MISSINGPROTOTYPES = ['-Wno-missing-prototypes']
CFLAGS_DISABLE_STRICTPROTOTYPES = ['-Wno-strict-prototypes']
CFLAGS_DISABLE_TYPELIMITS = ['-Wno-type-limits']
CFLAGS_DISABLE_WRITESTRINGS = ['-Wno-write-strings']
CFLAGS_ENABLE_ALL = ['-Wall']
CFLAGS_ENABLE_DIAGNOSTICSSHOWOPTION = ['-fdiagnostics-show-option']
CFLAGS_ENABLE_EMPTYBODY = ['-Wempty-body']
CFLAGS_ENABLE_FORMAT2 = ['-Wformat=2']
CFLAGS_ENABLE_FORMATEXTRAARGS = ['-Wformat-extra-args']
CFLAGS_ENABLE_FORMATNONLITERAL = ['-Wformat-nonliteral']
CFLAGS_ENABLE_FORMATSECURITY = ['-Wformat-security']
CFLAGS_ENABLE_FORMATZEROLENGTH = ['-Wformat-zero-length']
CFLAGS_ENABLE_IGNOREDQUALIFIERS = ['-Wignored-qualifiers']
CFLAGS_ENABLE_IMPLICITFUNCTIONDECLARATION = ['-Werror=implicit-function-declaration']
CFLAGS_ENABLE_MISSINGPROTOTYPES = ['-Wmissing-prototypes']
CFLAGS_ENABLE_STRICTPROTOTYPES = ['-Wstrict-prototypes']
CFLAGS_ENABLE_TYPELIMITS = ['-Wtype-limits']
CFLAGS_ENABLE_WRITESTRINGS = ['-Wwrite-strings']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_PERLEXT = ['-D_REENTRANT', '-D_GNU_SOURCE', '-DDEBIAN', '-fno-strict-aliasing', '-pipe', '-fstack-protector', '-I/usr/local/include', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-fPIC']
CFLAGS_PYEMBED = ['-pthread', '-fno-strict-aliasing', '-fwrapv', '-fno-strict-aliasing']
CFLAGS_PYEXT = ['-pthread', '-fno-strict-aliasing', '-fwrapv', '-fno-strict-aliasing']
CFLAGS_cshlib = ['-fPIC']
CFLAGS_cstlib = ['-fPIC', '-DPIC']
CFLAGS_gio2 = ['-pthread', '-pthread']
CFLAGS_gmodule2 = ['-pthread', '-pthread']
CFLAGS_gthread2 = ['-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread']
CFLAGS_gvfs = ['-pthread', '-pthread']
CLI_COMPAT_IMPL = 'unix'
CPPFLAGS_cxxshlib = ['-fPIC', '-DPIC']
CPPPATH_ST = '-I%s'
CXX = ['arm-arago-linux-gnueabi-gcc']
CXXFLAGS = ['-I/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include', '-I/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include', '-g', '-O0', '-fdiagnostics-show-option']
CXXFLAGS_DISABLE_DIAGNOSTICSSHOWOPTION = ['-fno-diagnostics-show-option']
CXXFLAGS_ENABLE_DIAGNOSTICSSHOWOPTION = ['-fdiagnostics-show-option']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_PYEMBED = ['-pthread', '-fno-strict-aliasing', '-fwrapv', '-fno-strict-aliasing']
CXXFLAGS_PYEXT = ['-pthread', '-fno-strict-aliasing', '-fwrapv', '-fno-strict-aliasing']
CXXFLAGS_cxxshlib = ['-fPIC']
CXXFLAGS_gio2 = ['-pthread', '-pthread']
CXXFLAGS_gmodule2 = ['-pthread', '-pthread']
CXXFLAGS_gthread2 = ['-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread']
CXXFLAGS_gvfs = ['-pthread', '-pthread']
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DATADIR = '/usr/share'
DATAROOTDIR = '/usr/share'
DEFINES = []
DEFINES_FSTATAT = ['_ATFILE_SOURCE=1']
DEFINES_PYEMBED = ['NDEBUG']
DEFINES_PYEXT = ['NDEBUG']
DEFINES_SEMTIMEDOP = ['_GNU_SOURCE=1']
DEFINES_ST = '-D%s'
DEFINES_avahiclient = ['_REENTRANT', '_REENTRANT']
DEFINES_avahiglib = ['_REENTRANT', '_REENTRANT']
DEFINES_mp4 = ['USE_TAGGING']
DEFINES_pulse = ['_REENTRANT']
DEFINES_sdl = ['_GNU_SOURCE=1', '_REENTRANT']
DEFINES_shm = ['_SEM_SEMUN_UNDEFINED']
DEST_BINFMT = 'elf'
DEST_CPU = 'arm'
DEST_OS = 'linux'
DOCDIR = '/usr/share/doc/xmms2'
DVIDIR = '/usr/share/doc/xmms2'
EXEC_PREFIX = '/usr'
EXTUTILS_TYPEMAP = ['/usr/share/perl/5.10/ExtUtils/typemap']
FLEX = '/usr/bin/flex'
FLEXFLAGS = ['-t']
GENPY_EXT = ['.genpy']
HAVE_ALSA = 1
HAVE_AVAHICLIENT = 1
HAVE_AVAHIGLIB = 1
HAVE_AVCODEC = 1
HAVE_CDDA = 1
HAVE_CURL = 1
HAVE_CURL_MULTI_STRERROR = 1
HAVE_DIRFD = 1
HAVE_DISCID = 1
HAVE_FAAD_H = 1
HAVE_FLAC = 1
HAVE_FSTATAT = 1
HAVE_GIO2 = 1
HAVE_GLIB2 = 1
HAVE_GME = 1
HAVE_GMODULE2 = 1
HAVE_GTHREAD2 = 1
HAVE_GVFS = 1
HAVE_G_FILE_QUERY_FILE_TYPE = 1
HAVE_JACK = 1
HAVE_LIBAVCODEC_AVCODEC_H = 1
HAVE_LOCALTIME_R = 1
HAVE_MAD = 1
HAVE_MMS = 1
HAVE_MODF = 1
HAVE_MODPLUG = 1
HAVE_MPG123 = 1
HAVE_MPG123_H = 1
HAVE_NANOSLEEP = 1
HAVE_OGG = 1
HAVE_OPENSSL = 1
HAVE_PULSE = 1
HAVE_READLINE = 1
HAVE_RL_FILENAME_DEQUOTING_FUNCTION = 1
HAVE_SDL = 1
HAVE_SEMCTL = 1
HAVE_SEMTIMEDOP = 1
HAVE_SIN = 1
HAVE_SNDFILE = 1
HAVE_SPEEX = 1
HAVE_SQLITE3 = 1
HAVE_STDIO_H = 1
HAVE_SYS_PRCTL_H = 1
HAVE_SYS_SELECT_H = 1
HAVE_SYS_SOUNDCARD_H = 1
HAVE_SYS_VFS_H = 1
HAVE_TREMOR_IVORBISFILE_H = 1
HAVE_VISUAL = 1
HAVE_VORBISENC = 1
HAVE_VORBISFILE = 1
HAVE_WAVPACK = 1
HAVE_XML2 = 1
HTMLDIR = '/usr/share/doc/xmms2'
INCLUDEDIR = '/usr/include'
INCLUDES_BOOST = '/root/boost_1_51_0'
INCLUDES_PERLEXT = ['/usr/lib/perl/5.10/CORE']
INCLUDES_PYEMBED = ['/usr/include/python2.6']
INCLUDES_PYEXT = ['/usr/include/python2.6']
INCLUDES_alsa = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/alsa']
INCLUDES_avahiglib = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_flac = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/FLAC']
INCLUDES_gio2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_glib2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_gmodule2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_gthread2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_gvfs = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_mms = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/glib-2.0', '/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib/glib-2.0/include']
INCLUDES_modplug = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/libmodplug']
INCLUDES_sdl = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/SDL']
INCLUDES_visual = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/libvisual-0.4']
INCLUDES_xml2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/include/libxml2']
INFODIR = '/usr/share/info'
INSTALLDIR_PERL_AUTO = '/usr/local/lib/perl/5.10.1/auto/Audio/XMMSClient'
INSTALLDIR_PERL_LIB = '/usr/local/lib/perl/5.10.1'
INSTALL_VIS_REFERENCE_CLIENTS = False
LIBDIR = '/usr/lib'
LIBEXECDIR = '/usr/libexec'
LIBPATH_PYEMBED = ['/usr/lib']
LIBPATH_PYTHON2.6 = ['/usr/lib']
LIBPATH_ST = '-L%s'
LIBPATH_alsa = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_avahiclient = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_avahiglib = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_avcodec = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_cdda = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_curl = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_discid = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_flac = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_gio2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_glib2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_gme = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_gmodule2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_gthread2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_gvfs = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_jack = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_mad = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_mms = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_modplug = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_mpg123 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_ogg = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_openssl = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_pulse = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_sdl = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_sndfile = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_speex = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_sqlite3 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_visual = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_vorbisenc = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_vorbisfile = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_wavpack = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIBPATH_xml2 = ['/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib']
LIB_PYEMBED = ['python2.6']
LIB_PYTHON2.6 = ['python2.6']
LIB_ST = '-l%s'
LIB_alsa = ['asound']
LIB_avahiclient = ['avahi-common', 'avahi-client']
LIB_avahiglib = ['avahi-glib', 'glib-2.0']
LIB_avcodec = ['avcodec']
LIB_cdda = ['cdio_cdda', 'cdio', 'm']
LIB_curl = ['curl']
LIB_discid = ['discid']
LIB_faad = ['faad']
LIB_flac = ['FLAC', 'm']
LIB_gio2 = ['gio-2.0', 'gobject-2.0', 'gmodule-2.0', 'gthread-2.0', 'rt', 'glib-2.0']
LIB_glib2 = ['glib-2.0']
LIB_gme = ['gme']
LIB_gmodule2 = ['gmodule-2.0', 'rt', 'glib-2.0']
LIB_gthread2 = ['gthread-2.0', 'rt', 'glib-2.0']
LIB_gvfs = ['gio-2.0', 'gobject-2.0', 'gmodule-2.0', 'gthread-2.0', 'rt', 'glib-2.0']
LIB_jack = ['jack', 'pthread', 'rt']
LIB_mad = ['mad', 'm']
LIB_math = ['m']
LIB_mms = ['mms', 'm', 'glib-2.0']
LIB_modplug = ['modplug']
LIB_mpg123 = ['mpg123']
LIB_ncurses = ['ncurses']
LIB_ogg = ['ogg']
LIB_openssl = ['ssl', 'crypto']
LIB_pulse = ['pulse']
LIB_readline = ['readline']
LIB_sdl = ['SDL', 'pthread']
LIB_sndfile = ['sndfile']
LIB_speex = ['speex']
LIB_sqlite3 = ['sqlite3']
LIB_tremor = ['vorbisidec']
LIB_visual = ['pthread', 'm', 'dl', 'visual-0.4']
LIB_vorbisenc = ['vorbisenc', 'vorbis', 'm', 'ogg']
LIB_vorbisfile = ['vorbisfile', 'vorbis', 'm', 'ogg']
LIB_wavpack = ['wavpack', 'm']
LIB_xml2 = ['xml2']
LINKFLAGS = ['-static-libgcc', '-L/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib', '-Wl,-rpath-link,/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib', '-Wl,-O1', '-Wl,--hash-style=gnu', '-static-libgcc', '-L/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib', '-Wl,-rpath-link,/usr/local/ti-sdk-am335x-evm/linux-devkit/arm-arago-linux-gnueabi/usr/lib', '-Wl,-O1', '-Wl,--hash-style=gnu']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_PERLEXT = ['-shared', '-O2', '-g', '-L/usr/local/lib', '-fstack-protector']
LINKFLAGS_PYEMBED = ['-Wl,-Bsymbolic-functions', '-pthread', '-Wl,-O1', '-Wl,-Bsymbolic-functions']
LINKFLAGS_PYEXT = ['-Wl,-Bsymbolic-functions', '-pthread', '-Wl,-O1', '-Wl,-Bsymbolic-functions']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINKFLAGS_gio2 = ['-pthread', '-pthread']
LINKFLAGS_gmodule2 = ['-pthread', '-Wl,--export-dynamic', '-pthread']
LINKFLAGS_gthread2 = ['-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread']
LINKFLAGS_gvfs = ['-pthread', '-pthread']
LINK_CC = ['arm-arago-linux-gnueabi-gcc']
LINK_CXX = ['arm-arago-linux-gnueabi-gcc']
LOCALEDIR = '/usr/share/locale'
LOCALSTATEDIR = '/usr/var'
MANDIR = '/usr/share/man'
MDNS_BACKEND = 'avahi'
NEWEST_WSCRIPT_SUBDIR = 1347103174.3572168
OLDINCLUDEDIR = '/usr/include'
PACKAGE = 'xmms2'
PDFDIR = '/usr/share/doc/xmms2'
PERL = '/usr/bin/perl'
PIXMAP_DIR = '/usr/share/pixmaps'
PKGCONFIG = '/usr/local/ti-sdk-am335x-evm/linux-devkit/bin/pkg-config'
PKGCONFIGDIR = '/usr/lib/pkgconfig'
PKGLIBDIR = '/usr/lib/xmms2'
PLUGINDIR = '/usr/lib/xmms2'
PREFIX = '/usr'
PSDIR = '/usr/share/doc/xmms2'
PYC = 1
PYCMD = '"import sys, py_compile;py_compile.compile(sys.argv[1], sys.argv[2])"'
PYFLAGS = ''
PYFLAGS_OPT = '-O'
PYO = 1
PYTHON = '/usr/bin/python'
PYTHONARCHDIR = '/usr/lib/python2.6/dist-packages'
PYTHONDIR = '/usr/lib/python2.6/dist-packages'
PYTHON_VERSION = '2.6'
RPATH_ST = '-Wl,-rpath,%s'
RUBY = '/usr/bin/ruby'
RUBY_VERSION = '1.8.7'
SBINDIR = '/usr/sbin'
SCRIPTDIR = '/usr/share/xmms2/scripts/startup.d'
SHAREDDIR = '/usr/share/xmms2'
SHAREDSTATEDIR = '/usr/com'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
SYSCONFDIR = '/etc/xmms2'
USERCACHEDIR = '.cache/xmms2'
USERCONFDIR = '.config/xmms2'
VERSION = '0.8 DrO_o (git commit: 6e6a9635-dirty)'
XMMS_DAAP_BACKEND = 'avahi'
XMMS_OPTIONAL_BUILD = ['pixmaps', 'src/clients/mdns', 'src/tools/sqlite2s4', 'src/clients/launcher', 'src/clients/nycli', 'src/clients/medialib-updater', 'src/clients/lib/xmmsclient++-glib', 'src/lib/s4/src/tools/s4', 'src/clients/et', 'src/clients/lib/perl', 'src/clients/vistest']
XMMS_OUTPUT_DEFAULT = 'alsa'
XMMS_OUTPUT_PLUGINS = [(-1, 'NONE'), (35, 'oss'), (25, 'pulse'), (5, 'diskwrite'), (40, 'alsa'), (10, 'null'), (4, 'airplay'), (20, 'jack')]
XMMS_PKGCONF_FILES = [('xmms2-client-cpp-glib', '-lxmmsclient-glib -lxmmsclient++-glib'), ('xmms2-plugin', ''), ('xmms2-client', '-lxmmsclient'), ('xmms2-client-glib', '-lxmmsclient-glib')]
XMMS_PLUGINS_ENABLED = ['speex', 'equalizer', 'nulstripper', 'xspf', 'oss', 'pulse', 'vorbis', 'replaygain', 'diskwrite', 'file', 'sndfile', 'curl', 'flv', 'tta', 'alsa', 'normalize', 'mpg123', 'null', 'midsquash', 'avcodec', 'cdda', 'airplay', 'gme', 'karaoke', 'cue', 'html', 'gvfs', 'modplug', 'xml', 'id3v2', 'pls', 'mad', 'asx', 'mms', 'wave', 'apefile', 'asf', 'flac', 'tremor', 'wavpack', 'rss', 'daap', 'faad', 'm3u', 'mp4', 'icymetaint', 'mid1', 'jack']
XMMS_VERSION = '0.8 DrO_o (git commit: 6e6a9635-dirty)'
XSUBPP = ['/usr/share/perl/5.10/ExtUtils/xsubpp']
cfg_files = ['/root/Hifi-Pod/player/server/xmms2-devel/_build_/xmms_configuration.h']
compat_impl = 'unix'
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
cxxprogram_PATTERN = '%s'
cxxshlib_PATTERN = 'lib%s.so'
cxxstlib_PATTERN = 'lib%s.a'
define_key = []
explicit_install_name = False
localtime_impl = 'unix'
mac_bundle_enabled = False
macbundle_PATTERN = '%s.bundle'
perlext_PATTERN = '%s.so'
pyext_PATTERN = '%s.so'
socket_impl = 'posix'
statfs_impl = 'linux'
thread_name_impl = 'prctl'
util_impl = 'unix'
visualization_impl = 'unixshm'
xmms_icon = False
xmms_shared_library = False
