######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 12 18:36:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core \
    gui \
    xml \
    network \
    phonon


# Input
HEADERS += HTTP_window.h MyMusicTest.h MyPlayer.h
SOURCES += HTTP_window.cpp main.cpp MyMusicTest.cpp MyPlayer.cpp
