######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 29 14:41:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += \
   core \
   phonon 

# Input
HEADERS += mediaplayer.h
FORMS += settings.ui
SOURCES += main.cpp mediaplayer.cpp
RESOURCES += mediaplayer.qrc
